/* =========================================================
   FOOD_DATA — 38 Provinsi dikelompokkan per Pulau/Kepulauan
   Setiap makanan: nama, provinsi, deskripsi (sejarah, cita
   rasa, filosofi budaya, sentra/lokasi tergabung dalam narasi)
   ========================================================= */

const FOOD_DATA = [
  {
    islandId: "sumatra",
    islandName: "Sumatra",
    icon: "🌋",
    color: "#C1440E",
    provinces: [
      { provinsi: "Aceh", makanan: "Mie Aceh", deskripsi: `Mie Aceh merupakan salah satu kuliner khas Provinsi Aceh yang mencerminkan pertemuan berbagai pengaruh budaya dalam sejarah perdagangan di wilayah tersebut. Kuliner ini berkembang melalui interaksi budaya Melayu, Arab, India, dan Tionghoa yang berlangsung melalui jalur perdagangan Aceh, kemudian beradaptasi dengan karakter bahan dan rempah lokal.\n\nMie Aceh memiliki cita rasa pedas dan gurih dengan penggunaan rempah kari yang kuat, menghasilkan aroma yang khas dan sensasi rasa yang hangat. Karakteristik rasanya ditandai oleh perpaduan rempah yang kompleks, tingkat kepedasan yang relatif kuat, serta rasa gurih yang menyatu dengan mi dan bahan pelengkap seperti daging, seafood, atau sayuran.\n\nDari perspektif budaya, Mie Aceh merepresentasikan keterbukaan masyarakat Aceh terhadap berbagai pengaruh budaya dari luar tanpa kehilangan karakter lokalnya. Kuliner ini dapat ditemukan secara luas di Kota Banda Aceh dan berbagai wilayah di Provinsi Aceh, dengan Banda Aceh berkembang sebagai salah satu pusat kuliner Mie Aceh.` },
      { provinsi: "Sumatera Utara", makanan: "Bika Ambon", deskripsi: `Bika Ambon merupakan salah satu kuliner yang sangat identik dengan Kota Medan, Provinsi Sumatera Utara, meskipun penggunaan nama "Ambon" sering menimbulkan anggapan bahwa makanan ini berasal dari Maluku. Dalam perkembangannya, Bika Ambon dikenal luas sebagai kue khas Medan dan menjadi salah satu produk kuliner yang melekat dengan identitas kota tersebut.\n\nBika Ambon memiliki cita rasa manis dan legit dengan aroma khas pandan dan serai yang memberikan karakter aromatik yang kuat. Teksturnya berpori, kenyal, lembut, dan memiliki struktur bersarang yang menjadi salah satu ciri sensorik utamanya.\n\nDari perspektif budaya, Bika Ambon merepresentasikan identitas kuliner Kota Medan sebagai kota perdagangan yang terbuka dan memiliki masyarakat yang multietnis. Sentra utama Bika Ambon berada di Kota Medan, terutama kawasan yang telah lama dikenal sebagai pusat produksi dan penjualan Bika Ambon.` },
      { provinsi: "Sumatera Barat", makanan: "Rendang", deskripsi: `Rendang merupakan kuliner khas Provinsi Sumatera Barat yang berakar kuat pada tradisi masyarakat Minangkabau dan memiliki kedudukan penting dalam identitas gastronomi daerah. Sejarah rendang berkaitan dengan teknik memasak yang dilakukan dalam waktu lama sehingga makanan dapat bertahan lebih lama dan mudah dibawa oleh masyarakat Minangkabau dalam perjalanan maupun ketika merantau.\n\nRendang memiliki cita rasa gurih dan pedas dengan karakter santan serta rempah-rempah yang sangat kuat. Proses pemasakan yang berlangsung secara perlahan memungkinkan bumbu meresap ke dalam daging dan menghasilkan cita rasa yang pekat, kompleks, serta aroma rempah yang khas.\n\nDalam konteks budaya, rendang memiliki filosofi yang berkaitan dengan kesabaran, ketahanan, musyawarah, serta tradisi merantau masyarakat Minangkabau. Rendang berkembang luas di berbagai wilayah Sumatera Barat, terutama Kota Padang, Bukittinggi, dan Payakumbuh.` },
      { provinsi: "Riau", makanan: "Gulai Ikan Patin", deskripsi: `Gulai Ikan Patin merupakan salah satu kuliner yang merepresentasikan hubungan erat masyarakat Provinsi Riau dengan lingkungan sungai dan sumber daya perairan. Kuliner ini berkembang dari tradisi Melayu yang memanfaatkan ikan sebagai sumber pangan utama masyarakat yang hidup di sekitar sungai.\n\nIkan patin yang memiliki daging lembut diolah menggunakan bumbu gulai sehingga menghasilkan cita rasa gurih, asam, segar, dan pedas ringan. Karakteristik rasanya ditandai oleh kelembutan daging ikan yang berpadu dengan kuah berbumbu, memberikan sensasi gurih sekaligus segar dan tidak terlalu berat.\n\nDalam perspektif budaya, Gulai Ikan Patin mencerminkan hubungan masyarakat Melayu Riau dengan sungai sebagai sumber kehidupan. Sentra kuliner ini berkembang terutama di Kota Pekanbaru serta kawasan sekitar aliran Sungai Siak dan Sungai Kampar.` },
      { provinsi: "Kepulauan Riau", makanan: "Otak-Otak", deskripsi: `Otak-Otak merupakan salah satu makanan khas Provinsi Kepulauan Riau yang berkembang dalam budaya masyarakat pesisir Melayu dan memanfaatkan ikan laut sebagai bahan pangan utama. Perkembangan kuliner ini tidak dapat dipisahkan dari karakter geografis Kepulauan Riau sebagai wilayah kepulauan yang memiliki sumber daya perikanan melimpah.\n\nOtak-Otak memiliki cita rasa gurih yang berasal dari ikan, disertai sedikit rasa pedas dan aroma khas daun yang digunakan dalam proses pembungkusan dan pembakaran. Karakteristik rasanya semakin kuat melalui proses pemanggangan yang menghasilkan aroma bakar atau asap, sementara teksturnya cenderung lembut dan kenyal.\n\nDari sisi budaya, Otak-Otak merepresentasikan identitas masyarakat maritim dan pesisir Kepulauan Riau. Sentra makanan ini berkembang di Kota Tanjungpinang, Kota Batam, Kabupaten Bintan, dan Kabupaten Karimun.` },
      { provinsi: "Jambi", makanan: "Tempoyak Ikan Patin", deskripsi: `Tempoyak Ikan Patin merupakan salah satu kuliner khas Provinsi Jambi yang memperlihatkan kreativitas masyarakat Melayu Sumatra dalam memanfaatkan hasil alam melalui teknik fermentasi. Kuliner ini menggunakan tempoyak, yaitu durian yang difermentasi, sebagai salah satu bahan utama yang memberikan karakter rasa dan aroma yang khas.\n\nTempoyak Ikan Patin memiliki cita rasa asam yang khas dari proses fermentasi durian, berpadu dengan rasa gurih ikan patin serta sensasi pedas dari bumbu yang digunakan. Karakteristik rasanya cukup kompleks karena mempertemukan rasa asam, gurih, pedas, dan aroma fermentasi durian yang kuat.\n\nDari perspektif budaya, makanan ini mencerminkan kemampuan masyarakat Jambi dalam memanfaatkan bahan pangan lokal sekaligus mempertahankan pengetahuan tradisional mengenai fermentasi. Kuliner ini banyak dikenal di Kota Jambi dan sepanjang Sungai Batanghari.` },
      { provinsi: "Sumatera Selatan", makanan: "Pempek", deskripsi: `Pempek merupakan salah satu ikon gastronomi Provinsi Sumatera Selatan yang sangat erat kaitannya dengan Kota Palembang sebagai kota sungai dan pusat perdagangan. Perkembangan pempek tidak dapat dipisahkan dari ketersediaan ikan sebagai sumber pangan masyarakat yang hidup di sekitar Sungai Musi.\n\nPempek memiliki cita rasa gurih yang berasal dari ikan dan tepung sagu, dengan tekstur kenyal yang menjadi karakteristik utamanya. Pengalaman rasa pempek semakin kompleks ketika disajikan bersama cuko, saus pendamping yang menghadirkan perpaduan rasa asam, pedas, dan manis, disertai aroma bawang putih dan rempah yang khas.\n\nDari sisi budaya, pempek mencerminkan kreativitas masyarakat di kawasan Sungai Musi dalam memanfaatkan sumber daya perairan. Kota Palembang menjadi sentra utama pempek, sementara kuliner ini juga berkembang di wilayah sekitar Sumatera Selatan.` },
      { provinsi: "Bengkulu", makanan: "Pendap", deskripsi: `Pendap merupakan makanan khas Provinsi Bengkulu yang memperlihatkan pemanfaatan bahan pangan lokal dan teknik memasak tradisional dalam menghasilkan hidangan dengan cita rasa yang kuat. Pendap berupa olahan ikan berbumbu yang dimasak dan dibungkus menggunakan daun talas, sehingga bumbu dapat meresap selama proses pemasakan yang berlangsung relatif lama.\n\nCita rasanya cenderung pedas dan gurih dengan aroma rempah yang kuat, sementara proses pemasakan dalam balutan daun menghasilkan karakter aroma dan tekstur yang khas. Perpaduan ikan dengan bumbu rempah menciptakan rasa yang kaya, sedangkan daun talas berperan memberikan karakter tersendiri.\n\nDari perspektif budaya, Pendap mencerminkan kesederhanaan, ketekunan, serta kearifan masyarakat Bengkulu dalam memanfaatkan bahan-bahan yang tersedia di lingkungan sekitarnya. Kuliner ini dikenal luas di Kota Bengkulu dan wilayah pesisir seperti Seluma, Bengkulu Selatan, dan Kaur.` },
      { provinsi: "Lampung", makanan: "Seruit", deskripsi: `Seruit merupakan kuliner khas Provinsi Lampung yang tidak hanya dikenal sebagai hidangan berbahan ikan, tetapi juga sebagai bagian dari tradisi makan bersama masyarakat Lampung. Seruit pada dasarnya merupakan perpaduan ikan dengan sambal dan lalapan yang dikonsumsi secara bersama-sama, sehingga makanan ini memiliki dimensi sosial yang kuat.\n\nDari sisi rasa, Seruit menghadirkan perpaduan rasa pedas, asam, gurih, dan segar. Rasa gurih berasal dari ikan yang menjadi bahan utama, sedangkan sambal memberikan sensasi pedas dan dapat diperkaya dengan unsur asam melalui bahan seperti tempoyak atau jeruk.\n\nDalam perspektif budaya, Seruit merepresentasikan nilai kebersamaan, kekeluargaan, dan budaya makan bersama yang menjadi bagian dari kehidupan sosial masyarakat Lampung. Kuliner ini berkembang di Kota Bandar Lampung serta wilayah Pesawaran, Lampung Selatan, dan Tanggamus.` },
      { provinsi: "Kepulauan Bangka Belitung", makanan: "Lempah Kuning", deskripsi: `Lempah Kuning merupakan salah satu kuliner khas Provinsi Kepulauan Bangka Belitung yang merepresentasikan karakter gastronomi masyarakat Melayu pesisir dan kedekatan mereka dengan sumber daya laut. Hidangan ini umumnya menggunakan ikan sebagai bahan utama yang dimasak dalam kuah berbumbu dengan karakter warna kuning yang berasal dari kunyit.\n\nLempah Kuning memiliki cita rasa asam, pedas, segar, dan gurih, dengan kuah yang ringan tetapi kaya akan aroma rempah. Karakteristik rasa tersebut memberikan sensasi segar yang berpadu dengan gurihnya ikan laut serta kepedasan bumbu.\n\nDari perspektif budaya, Lempah Kuning mencerminkan kedekatan masyarakat Bangka Belitung dengan laut sekaligus pemanfaatan rempah dalam tradisi kuliner Melayu. Kuliner ini dikenal luas di Kota Pangkalpinang, Kabupaten Bangka, dan Kabupaten Belitung.` },
    ]
  },
  {
    islandId: "jawa",
    islandName: "Jawa",
    icon: "🏯",
    color: "#8B5E3C",
    provinces: [
      { provinsi: "Banten", makanan: "Sate Bandeng", deskripsi: `Sate Bandeng merupakan salah satu kuliner khas Provinsi Banten yang memperlihatkan keterampilan masyarakat dalam mengolah ikan bandeng menjadi hidangan yang lebih praktis untuk dikonsumsi. Kuliner ini berkembang melalui teknik pengolahan bandeng dengan mengeluarkan duri dan mengolah kembali daging ikan bersama bumbu sebelum dimasukkan kembali ke dalam kulit ikan dan dipanggang.\n\nProses tersebut menghasilkan cita rasa gurih, sedikit manis, dan kaya bumbu, dengan tekstur daging yang lembut serta relatif halus tanpa gangguan duri. Proses pembakaran menghasilkan aroma khas yang memperkuat karakter sensoriknya.\n\nDari perspektif budaya, Sate Bandeng mencerminkan ketelitian dan kehalusan teknik pengolahan pangan sekaligus menjadi bagian dari warisan kuliner masyarakat pesisir Banten. Kuliner ini terutama dikenal sebagai makanan khas Kota Serang dan Kabupaten Serang.` },
      { provinsi: "DKI Jakarta", makanan: "Kerak Telor", deskripsi: `Kerak Telor merupakan salah satu kuliner khas masyarakat Betawi yang telah menjadi bagian dari identitas gastronomi Jakarta dan dikenal luas sejak masa kolonial. Makanan ini dibuat menggunakan beras ketan dan telur yang dimasak hingga menghasilkan bagian bawah yang bertekstur renyah, kemudian dipadukan dengan serundeng kelapa.\n\nKerak Telor memiliki cita rasa gurih dan renyah dengan sedikit rasa manis yang berasal dari serundeng, sementara aroma kelapa sangrai dan bumbu memberikan karakter sensorik yang khas. Perpaduan tekstur renyah, kelembutan telur, dan aroma kelapa sangrai menghasilkan pengalaman makan yang khas.\n\nDalam perspektif budaya, Kerak Telor memiliki posisi penting sebagai representasi identitas masyarakat Betawi. Kuliner ini dapat ditemukan di berbagai kegiatan budaya, terutama kawasan Setu Babakan sebagai pusat pelestarian budaya Betawi.` },
      { provinsi: "Jawa Barat", makanan: "Nasi Timbel", deskripsi: `Nasi Timbel merupakan salah satu kuliner khas Jawa Barat yang berkembang dari tradisi masyarakat Sunda, terutama berkaitan dengan kebiasaan membawa bekal makanan. Hidangan ini memiliki ciri khas berupa nasi hangat yang dibungkus menggunakan daun pisang, sehingga aroma alami daun dapat meresap.\n\nDari sisi cita rasa, Nasi Timbel cenderung gurih dan lembut, sementara penyajiannya bersama lalapan, sambal, ikan, tahu, tempe, atau lauk lainnya menghasilkan perpaduan rasa gurih, pedas, segar, dan beragam tekstur.\n\nDari perspektif budaya, makanan ini mencerminkan kesederhanaan dan kedekatan masyarakat Sunda dengan alam. Nasi Timbel dikenal luas di Kota Bandung dan wilayah Jawa Barat lain seperti Garut, Sumedang, dan Cianjur.` },
      { provinsi: "Jawa Tengah", makanan: "Lumpia Semarang", deskripsi: `Lumpia Semarang merupakan salah satu kuliner khas Jawa Tengah yang menjadi contoh nyata akulturasi antara budaya Jawa dan Tionghoa. Kuliner ini berkembang di Kota Semarang melalui proses interaksi masyarakat lokal dan pendatang yang kemudian menghasilkan perpaduan teknik, bahan, dan cita rasa dalam satu hidangan.\n\nLumpia Semarang memiliki cita rasa gurih dan sedikit manis dengan isian yang umumnya menggunakan rebung sebagai bahan yang memberikan aroma serta tekstur khas. Kulit lumpia yang dimasak hingga renyah berpadu dengan isian rebung yang lembut, menciptakan kontras tekstur yang menarik.\n\nDari perspektif budaya, makanan ini merepresentasikan harmoni antara budaya lokal Jawa dan budaya pendatang Tionghoa. Sentra utamanya berada di Kota Semarang, terutama kawasan Pecinan.` },
      { provinsi: "DI Yogyakarta", makanan: "Gudeg", deskripsi: `Gudeg merupakan salah satu kuliner yang sangat melekat dengan identitas gastronomi Daerah Istimewa Yogyakarta dan dikenal sebagai hidangan berbahan dasar nangka muda yang dimasak melalui proses yang relatif lama, memungkinkan bumbu meresap secara perlahan.\n\nGudeg memiliki rasa manis yang dominan dengan perpaduan gurih dari santan dan aroma rempah seperti daun salam serta lengkuas, sementara gula kelapa memberikan karakter manis yang menjadi ciri utama hidangan ini.\n\nDalam perspektif budaya, Gudeg merepresentasikan nilai kesabaran, kelembutan, keharmonisan, serta identitas masyarakat Jawa-Yogyakarta. Sentra Gudeg yang paling dikenal berada di kawasan Wijilan, Kota Yogyakarta, selain Sleman dan Bantul.` },
      { provinsi: "Jawa Timur", makanan: "Rawon", deskripsi: `Rawon merupakan salah satu kuliner khas Jawa Timur yang memiliki karakteristik kuat dan mudah dikenali melalui warna kuahnya yang gelap serta penggunaan kluwek sebagai bahan utama bumbu. Hidangan ini berkembang dalam tradisi kuliner masyarakat Jawa Timur dengan perpaduan rempah yang menghasilkan cita rasa kaya.\n\nRawon memiliki cita rasa gurih dengan sedikit rasa pahit khas kluwek yang berpadu dengan rempah-rempah lainnya, sehingga menghasilkan kuah yang pekat, aromatik, dan kompleks. Daging sapi yang dimasak hingga empuk menyerap bumbu secara optimal.\n\nDari perspektif budaya, Rawon mencerminkan kekayaan rempah dan keberanian masyarakat Jawa Timur dalam mempertahankan cita rasa yang kuat. Kuliner ini dikenal luas di Kota Surabaya, Kota Malang, Pasuruan, dan Probolinggo.` },
    ]
  },
  {
    islandId: "bali-nusra",
    islandName: "Bali & Nusa Tenggara",
    icon: "🌺",
    color: "#C9A961",
    provinces: [
      { provinsi: "Bali", makanan: "Ayam Betutu", deskripsi: `Ayam Betutu merupakan salah satu kuliner tradisional Bali yang memiliki keterkaitan erat dengan kehidupan adat dan ritual masyarakat Bali. Hidangan ini dibuat menggunakan ayam yang dibumbui dengan berbagai rempah dalam base genep, yaitu perpaduan bumbu khas Bali yang menghasilkan cita rasa dan aroma yang kompleks.\n\nAyam Betutu memiliki cita rasa pedas dan gurih dengan karakter rempah yang kuat dan meresap hingga ke dalam daging akibat proses pemasakan yang dilakukan secara perlahan. Perpaduan cabai, bawang, kunyit, lengkuas, jahe, dan serai memberikan aroma yang khas serta sensasi rasa yang intens.\n\nDalam perspektif budaya, Ayam Betutu memiliki hubungan dengan persembahan, spiritualitas, dan berbagai kegiatan ritual masyarakat Bali. Kuliner ini berkembang di Gianyar, Klungkung, Bangli, Badung, serta Kota Denpasar.` },
      { provinsi: "Nusa Tenggara Barat", makanan: "Ayam Taliwang", deskripsi: `Ayam Taliwang merupakan kuliner khas Nusa Tenggara Barat yang sangat identik dengan masyarakat Sasak di Pulau Lombok. Hidangan ini berkembang sebagai bagian dari tradisi kuliner masyarakat Lombok dan dikenal melalui penggunaan ayam yang dibumbui dengan rempah serta sambal bercita rasa kuat.\n\nAyam Taliwang memiliki cita rasa pedas yang tajam dengan perpaduan gurih dan aroma smoky yang diperoleh melalui proses pembakaran. Penggunaan cabai, bawang, terasi, kencur, dan tomat menghasilkan sensasi pedas, gurih, sedikit asam, serta aroma rempah yang kuat.\n\nDari perspektif budaya, karakter rasa Ayam Taliwang yang kuat dan pedas sering dipandang merepresentasikan karakter masyarakat Lombok yang tegas dan ekspresif. Sentra utamanya berada di Kota Mataram dan seluruh Pulau Lombok.` },
      { provinsi: "Nusa Tenggara Timur", makanan: "Se'i Sapi", deskripsi: `Se'i Sapi merupakan salah satu kuliner khas Nusa Tenggara Timur yang berasal dari tradisi pengolahan daging masyarakat Timor melalui teknik pengasapan. Teknik tersebut berkembang sebagai bentuk pengetahuan lokal dalam mengolah dan mengawetkan daging sehingga dapat disimpan lebih lama.\n\nSe'i Sapi memiliki cita rasa gurih dan sedikit asin dengan aroma asap yang menjadi karakter sensorik utamanya. Proses pengasapan memberikan aroma khas pada daging sekaligus menghasilkan tekstur yang relatif lembut, terutama saat dipadukan dengan sambal lu'at yang memberikan sensasi pedas dan segar.\n\nDari perspektif budaya, Se'i Sapi mencerminkan kecerdasan lokal masyarakat dalam memanfaatkan teknik pengawetan pangan. Kota Kupang menjadi sentra utama, selain wilayah Timor Tengah Selatan, Timor Tengah Utara, dan Belu.` },
    ]
  },
  {
    islandId: "kalimantan",
    islandName: "Kalimantan",
    icon: "🌳",
    color: "#4E7C59",
    provinces: [
      { provinsi: "Kalimantan Barat", makanan: "Bubur Pedas Sambas", deskripsi: `Bubur Pedas Sambas merupakan kuliner khas Kalimantan Barat yang berakar pada tradisi masyarakat Melayu Sambas dan memperlihatkan kekayaan bahan pangan serta tumbuhan lokal. Hidangan ini dibuat menggunakan beras dan berbagai sayuran serta rempah yang menghasilkan makanan dengan tekstur lembut.\n\nBubur Pedas memiliki cita rasa gurih, pedas, dan herbal, dengan karakteristik rasa yang berasal dari perpaduan rempah, sayuran, serta bahan-bahan lokal. Aroma herbal yang khas dan keragaman tekstur dari berbagai sayuran memberikan pengalaman sensorik yang berbeda.\n\nDari perspektif budaya, Bubur Pedas Sambas mencerminkan kebersamaan dan tradisi masyarakat Melayu dalam mengolah bahan pangan lokal. Kabupaten Sambas merupakan sentra utama, berkembang pula di Singkawang dan Pontianak.` },
      { provinsi: "Kalimantan Tengah", makanan: "Juhu Singkah", deskripsi: `Juhu Singkah merupakan salah satu makanan khas Kalimantan Tengah yang merepresentasikan kekayaan pangan lokal dan hubungan erat masyarakat Dayak dengan lingkungan hutan. Hidangan ini menggunakan rotan muda atau singkah sebagai bahan utama, diolah bersama bahan dan bumbu lainnya.\n\nJuhu Singkah memiliki cita rasa gurih, sedikit pahit, dan segar, dengan rasa pahit alami dari rotan muda yang menjadi karakter sensorik yang membedakannya dari kuliner berbahan sayuran pada umumnya.\n\nDari perspektif budaya, Juhu Singkah mencerminkan hubungan masyarakat Dayak dengan hutan sebagai sumber pangan. Kuliner ini ditemukan di Kota Palangka Raya dan sejumlah kabupaten seperti Gunung Mas, Kapuas, dan Katingan.` },
      { provinsi: "Kalimantan Selatan", makanan: "Soto Banjar", deskripsi: `Soto Banjar merupakan salah satu kuliner khas Kalimantan Selatan yang sangat erat dengan identitas masyarakat Banjar. Hidangan ini dikenal melalui kuah yang kaya rempah dengan karakter rasa yang gurih, harum, dan relatif ringan, berbeda dari berbagai jenis soto di wilayah Indonesia lainnya.\n\nKuah yang kaya rempah berpadu dengan daging ayam dan bahan pelengkap lainnya, menghasilkan sensasi gurih dan hangat dengan tekstur yang lembut. Keseimbangan antara kaldu, rempah aromatik, dan bahan pelengkap menjadi karakteristik utamanya.\n\nDari perspektif budaya, Soto Banjar mencerminkan keramahan dan kehangatan keluarga masyarakat Banjar. Kuliner ini berkembang luas di Kota Banjarmasin, Banjarbaru, dan Kabupaten Banjar.` },
      { provinsi: "Kalimantan Timur", makanan: "Nasi Bekepor", deskripsi: `Nasi Bekepor merupakan makanan tradisional Kalimantan Timur yang memiliki keterkaitan dengan warisan budaya Kutai dan sejarah kerajaan di wilayah tersebut. Hidangan ini merupakan olahan nasi yang dimasak dengan bahan dan bumbu tertentu.\n\nNasi Bekepor menghasilkan cita rasa gurih, sedikit pedas, serta aroma khas ikan asin dan rempah. Penggunaan ikan asin turut memberikan kedalaman rasa, sedangkan rempah memperkuat aroma dan sensasi rasa yang lebih kompleks.\n\nDari perspektif budaya, Nasi Bekepor memiliki nilai penting sebagai bagian dari warisan kuliner masyarakat Kutai. Kuliner ini terutama dikenal di Kabupaten Kutai Kartanegara (Tenggarong) serta Kota Samarinda.` },
      { provinsi: "Kalimantan Utara", makanan: "Kepiting Soka", deskripsi: `Kepiting Soka merupakan salah satu kuliner yang merepresentasikan kekayaan sumber daya pesisir Provinsi Kalimantan Utara, terutama kawasan Tarakan yang dikenal memiliki potensi perikanan dan budidaya kepiting. Kepiting soka memiliki karakteristik khusus karena dikonsumsi bersama cangkangnya yang masih lunak.\n\nDari sisi cita rasa, makanan ini memiliki rasa gurih dan sedikit manis yang merupakan karakter alami daging kepiting, dengan tekstur daging yang lembut dan bagian cangkang yang renyah ketika digoreng atau dimasak dengan bumbu tertentu.\n\nDalam perspektif budaya, Kepiting Soka mencerminkan kekayaan laut, ekonomi pesisir, serta budaya maritim masyarakat Kalimantan Utara. Sentra utamanya berada di Kota Tarakan.` },
    ]
  },
  {
    islandId: "sulawesi",
    islandName: "Sulawesi",
    icon: "🐚",
    color: "#2F6690",
    provinces: [
      { provinsi: "Sulawesi Utara", makanan: "Tinutuan", deskripsi: `Tinutuan atau Bubur Manado merupakan salah satu kuliner khas Sulawesi Utara yang mencerminkan pemanfaatan beragam sayuran dan bahan pangan lokal dalam kehidupan masyarakat. Hidangan ini berupa bubur yang diolah menggunakan aneka sayuran lokal, menghasilkan cita rasa gurih, segar, dan relatif ringan.\n\nKeragaman bahan memberikan tekstur dan aroma yang berlapis, sementara sayuran menjadi unsur penting yang membedakan Tinutuan dari bubur berbahan dasar beras lainnya. Tinutuan kerap dipadukan dengan sambal atau lauk pendamping yang memberikan tambahan rasa pedas dan gurih.\n\nDari perspektif budaya, Tinutuan merepresentasikan kebersamaan, keterbukaan, dan harmoni masyarakat Manado. Kota Manado menjadi sentra utama, berkembang pula di wilayah Minahasa.` },
      { provinsi: "Gorontalo", makanan: "Binte Biluhuta", deskripsi: `Binte Biluhuta merupakan salah satu makanan khas Provinsi Gorontalo berupa sup berbahan dasar jagung yang mencerminkan pemanfaatan pangan lokal dalam kehidupan masyarakat, mencerminkan karakter agraris sekaligus pesisir Gorontalo.\n\nBinte Biluhuta memiliki cita rasa manis alami dari jagung yang berpadu dengan rasa gurih, segar, serta sedikit pedas dan asam. Tekstur jagung memberikan sensasi khas dalam setiap suapan, sementara bahan pendamping dari hasil laut dapat memperkaya cita rasa hidangan.\n\nDari perspektif budaya, Binte Biluhuta mencerminkan kesuburan dan pemanfaatan pangan lokal masyarakat Gorontalo. Kuliner ini dikenal luas di Kota Gorontalo dan kabupaten sekitarnya seperti Bone Bolango dan Boalemo.` },
      { provinsi: "Sulawesi Tengah", makanan: "Kaledo", deskripsi: `Kaledo merupakan salah satu kuliner khas Sulawesi Tengah yang berkembang dalam tradisi masyarakat Kaili dan dikenal sebagai hidangan berbahan tulang kaki sapi. Penggunaan bagian tulang dan sumsum menunjukkan pemanfaatan bahan pangan secara menyeluruh dalam tradisi kuliner lokal.\n\nKaledo memiliki cita rasa gurih, asam, dan pedas dengan kuah yang relatif ringan tetapi memiliki karakter rasa yang kuat. Sumsum yang terdapat pada tulang kaki memberikan tekstur lembut dan rasa gurih yang lebih kaya.\n\nDari perspektif budaya, Kaledo mencerminkan kekuatan dan keterbukaan masyarakat Kaili di Sulawesi Tengah. Kota Palu dikenal sebagai pusat utama kuliner Kaledo, selain Kabupaten Sigi dan Donggala.` },
      { provinsi: "Sulawesi Barat", makanan: "Jepa", deskripsi: `Jepa merupakan makanan khas Provinsi Sulawesi Barat yang memiliki kedudukan penting dalam tradisi pangan masyarakat Mandar. Makanan ini berbahan dasar singkong atau sagu dan secara tradisional berfungsi sebagai salah satu sumber pangan pokok masyarakat pesisir.\n\nJepa memiliki cita rasa yang cenderung tawar hingga gurih dengan tekstur yang padat dan sesuai dipadukan dengan berbagai lauk, khususnya ikan. Ketika dipadukan dengan ikan dan sambal, Jepa menghasilkan kombinasi rasa gurih, asin, dan pedas yang lebih kompleks.\n\nDari perspektif budaya, Jepa merepresentasikan kesederhanaan, ketahanan pangan, serta kehidupan masyarakat pesisir Mandar. Kuliner ini terutama dikenal di Kabupaten Majene dan Polewali Mandar.` },
      { provinsi: "Sulawesi Selatan", makanan: "Coto Makassar", deskripsi: `Coto Makassar merupakan salah satu kuliner tradisional Provinsi Sulawesi Selatan yang memiliki sejarah panjang dalam kehidupan masyarakat Makassar dan telah berkembang menjadi salah satu ikon gastronomi daerah. Hidangan ini menggunakan daging dan bagian-bagian tertentu dari sapi yang dimasak dengan perpaduan rempah.\n\nKarakteristik utama Coto Makassar terletak pada kuahnya yang kaya rempah dengan aroma yang kuat dan rasa yang mendalam. Penggunaan kacang tanah sangrai sebagai bagian dari bumbu turut memberikan kekayaan rasa dan tekstur pada kuah.\n\nDari perspektif budaya, Coto Makassar mencerminkan nilai kehormatan, kebersamaan, serta identitas masyarakat Bugis-Makassar. Kota Makassar menjadi sentra utama, berkembang pula di Gowa, Maros, dan Takalar.` },
      { provinsi: "Sulawesi Tenggara", makanan: "Sinonggi", deskripsi: `Sinonggi merupakan salah satu makanan khas Provinsi Sulawesi Tenggara yang berbahan dasar sagu dan memiliki keterkaitan erat dengan tradisi pangan masyarakat Tolaki. Makanan ini memiliki tekstur kenyal dan lembut dengan cita rasa yang cenderung tawar sehingga mampu menyerap rasa dari kuah dan lauk yang menyertainya.\n\nKetika disantap bersama kuah ikan, sayuran, atau lauk berbumbu, Sinonggi dapat menghadirkan perpaduan rasa gurih, pedas, dan segar sesuai dengan karakter kuah atau lauk yang digunakan.\n\nDari perspektif budaya, Sinonggi mencerminkan ketahanan pangan, kebersamaan, serta hubungan masyarakat Tolaki dengan lingkungan alam. Kuliner ini dikenal terutama di Kota Kendari dan wilayah Konawe.` },
    ]
  },
  {
    islandId: "maluku",
    islandName: "Maluku",
    icon: "🐠",
    color: "#B5562A",
    provinces: [
      { provinsi: "Maluku", makanan: "Papeda", deskripsi: `Papeda merupakan salah satu makanan pokok khas Provinsi Maluku yang berbahan dasar sagu dan memiliki kedudukan penting dalam tradisi pangan masyarakat Maluku. Sebagai wilayah kepulauan yang kaya sumber daya laut sekaligus tanaman sagu, masyarakat Maluku memanfaatkan sagu sebagai sumber pangan utama.\n\nPapeda memiliki cita rasa yang cenderung tawar dengan tekstur yang kenyal dan lengket, sehingga umumnya disantap bersama ikan yang dimasak dengan kuah berbumbu. Karakteristik rasa yang netral menjadikannya sangat sesuai untuk menyerap cita rasa lauk dan kuah pendamping.\n\nDari perspektif budaya, Papeda mencerminkan kehidupan, ketahanan pangan, dan kebersamaan masyarakat Maluku. Papeda dikenal di Kota Ambon dan wilayah Maluku Tengah, Seram Bagian Barat, dan Buru.` },
      { provinsi: "Maluku Utara", makanan: "Gohu Ikan", deskripsi: `Gohu Ikan merupakan salah satu kuliner khas Provinsi Maluku Utara yang mencerminkan kedekatan masyarakat pesisir dengan sumber daya laut. Makanan ini dikenal sebagai olahan ikan mentah yang berkembang terutama dalam tradisi kuliner masyarakat Ternate dan wilayah kepulauan sekitarnya.\n\nGohu Ikan memiliki cita rasa yang segar, asam, pedas, dan gurih yang berasal dari ikan segar serta perpaduan bahan pelengkap dan bumbu yang digunakan. Karakteristik rasanya menonjolkan kesegaran ikan sebagai bahan utama, diperkaya sensasi asam dan pedas.\n\nDari perspektif budaya, Gohu Ikan merepresentasikan kedekatan masyarakat Maluku Utara dengan laut. Kota Ternate menjadi salah satu sentra utama kuliner ini.` },
    ]
  },
  {
    islandId: "papua",
    islandName: "Papua",
    icon: "🦜",
    color: "#3E6B4F",
    provinces: [
      { provinsi: "Papua Barat", makanan: "Ikan Bakar Manokwari", deskripsi: `Ikan Bakar Manokwari merupakan salah satu kuliner khas Papua Barat yang berkembang dari tradisi masyarakat pesisir Manokwari dalam memanfaatkan hasil laut sebagai sumber pangan. Hidangan ini mengolah ikan melalui proses pembakaran yang menghasilkan aroma khas sekaligus mempertahankan cita rasa alami ikan.\n\nIkan Bakar Manokwari memiliki cita rasa gurih dengan sensasi pedas yang berasal dari sambal khas yang menjadi pendamping utama, sementara proses pembakaran memberikan aroma asap yang memperkaya pengalaman sensoriknya.\n\nDari perspektif budaya, Ikan Bakar Manokwari merepresentasikan identitas masyarakat pesisir dan kekayaan sumber daya laut. Kabupaten Manokwari menjadi sentra utama kuliner ini.` },
      { provinsi: "Papua Barat Daya", makanan: "Sagu Lempeng", deskripsi: `Sagu Lempeng merupakan salah satu makanan tradisional Provinsi Papua Barat Daya yang berbahan dasar sagu dan mencerminkan pentingnya sagu dalam sistem pangan masyarakat Papua. Makanan ini diolah menjadi bentuk lempengan yang kemudian dikeringkan sehingga menghasilkan pangan dengan daya simpan yang relatif baik.\n\nDari sisi cita rasa, Sagu Lempeng cenderung tawar dengan karakter tekstur yang kering, padat, dan renyah atau keras. Karakter rasa yang netral membuatnya dapat dikonsumsi sebagai pangan pendamping dan dipadukan dengan lauk atau minuman tertentu.\n\nDari perspektif budaya, Sagu Lempeng merepresentasikan kemampuan masyarakat dalam mengolah sagu sebagai sumber pangan penting. Kota Sorong dan Kabupaten Sorong menjadi wilayah penting pengembangannya.` },
      { provinsi: "Papua", makanan: "Papeda Ikan Kuah Kuning", deskripsi: `Papeda Ikan Kuah Kuning merupakan salah satu hidangan yang merepresentasikan perpaduan antara sumber pangan darat dan laut dalam tradisi gastronomi masyarakat Papua. Papeda berbahan dasar sagu menjadi unsur pangan utama dari daratan, sedangkan ikan merepresentasikan kekayaan sumber daya perairan.\n\nPapeda memiliki rasa yang cenderung tawar dan tekstur kenyal, sehingga berfungsi sebagai pangan yang menyerap cita rasa kuah pendamping. Kuah ikan kuning memberikan rasa gurih dan asam yang segar dengan aroma rempah yang khas.\n\nDari perspektif budaya, hidangan ini mencerminkan harmoni antara daratan dan laut. Hidangan ini dikenal luas di Kota Jayapura dan wilayah Papua yang mempertahankan tradisi pangan berbasis sagu.` },
      { provinsi: "Papua Tengah", makanan: "Ulat Sagu", deskripsi: `Ulat Sagu merupakan salah satu pangan tradisional yang dikenal dalam kehidupan masyarakat di wilayah Papua Tengah dan mencerminkan pemanfaatan sumber daya alam secara menyeluruh. Pangan ini berasal dari pemanfaatan batang sagu, khususnya bagian yang menjadi habitat larva kumbang sagu.\n\nUlat Sagu memiliki cita rasa gurih dan berlemak dengan tekstur yang relatif lembut. Karakteristik rasa tersebut semakin terasa ketika ulat sagu diolah dengan cara tradisional, termasuk melalui proses pemanggangan.\n\nDari perspektif budaya, Ulat Sagu mencerminkan pemanfaatan alam secara menyeluruh sekaligus pengetahuan ekologis lokal yang diwariskan antargenerasi. Kabupaten Mimika dan Nabire dikaitkan dengan tradisi pemanfaatan sumber daya sagu ini.` },
      { provinsi: "Papua Pegunungan", makanan: "Ubi Bakar", deskripsi: `Ubi Bakar merupakan salah satu pangan tradisional yang memiliki peranan penting dalam kehidupan masyarakat di wilayah Papua Pegunungan. Ubi telah lama menjadi salah satu sumber pangan penting bagi masyarakat pegunungan karena dapat dibudidayakan dan diolah sesuai kondisi lingkungan setempat.\n\nPengolahan dengan cara dibakar menghasilkan cita rasa manis alami, tekstur yang lembut pada bagian dalam, serta aroma khas pembakaran yang memperkaya pengalaman sensorik.\n\nDari perspektif budaya, Ubi Bakar merepresentasikan kesederhanaan, kerja komunal, dan ketahanan hidup masyarakat pegunungan. Kuliner ini ditemukan di Kabupaten Jayawijaya (Wamena), Lanny Jaya, Tolikara, Yahukimo, dan Pegunungan Bintang.` },
      { provinsi: "Papua Selatan", makanan: "Sagu Sep", deskripsi: `Sagu Sep merupakan salah satu olahan sagu yang merepresentasikan pentingnya tanaman sagu dalam sistem pangan masyarakat Papua Selatan. Makanan ini berkembang dalam lingkungan yang memiliki kawasan rawa dan ekosistem yang mendukung pertumbuhan sagu.\n\nSagu Sep memiliki cita rasa yang cenderung tawar dengan tekstur yang padat, tetapi dapat memberikan rasa gurih ketika dipadukan dengan lauk pendamping seperti ikan, daging, atau lauk berbumbu.\n\nDari perspektif budaya, Sagu Sep mencerminkan identitas pangan masyarakat Papua Selatan, keberlanjutan pemanfaatan sumber daya alam rawa, serta budaya berbagi. Kabupaten Merauke menjadi salah satu sentra penting, selain Mappi, Boven Digoel, dan Asmat.` },
    ]
  },
];

/* Helper: cari makanan berdasarkan islandId + index provinsi */
function getFoodByRef(islandId, provIndex) {
  const island = FOOD_DATA.find(i => i.islandId === islandId);
  if (!island) return null;
  return island.provinces[provIndex] || null;
}
